//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microlive.Model.Interfaces;

namespace Microlive.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag:Interfaces.IModel, IModelWithSinglePk
    {
        public System.Guid Id { get; set; }
        public System.Guid ImageId { get; set; }
        public System.Guid CommentId { get; set; }
        public string Text { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual Image Image { get; set; }
    }
}
